### PR TITLE
Math Magicians: tests

### PR DESCRIPTION
**Pull request by ridwanediallo**
# Project requirements:
-Set up React Testing Library.
 :one: Follow the instructions in the official [documentation](https://testing-library.com/docs/react-testing-library/intro).
:two: You don't need to setup Jest (it's included in Create React App).
- Write unit tests for the files operate.js and calculate.js using Jest.
- Create unit tests for all React components:
 :one: Use Jest snapshots to test the components.
:two: Use React Testing Library to simulate user interaction.
-  Run your full tests suite using Jest. All tests should pass.

### CODE REVIEW

**Review by TedLivist — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @ridwanediallo and @SaidRasinlic,

Good job so far!
✔️ Good documentation
✔️ Use of RTL for user simulation
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] **You are missing snapshot tests for your components. Kindly add them.**

- [x] **You are missing tests for the `calculate.js` operations. Kindly add them.**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ridwanediallo** [comment]
Hello @TedLivist, thank you for the review. However, the changes you are requesting are already done. Our components have snapshot tests and We are testing the calculator.js operations.

**Comment by TedLivist** [comment]
@ridwanediallo, you are right. I missed the `calculate.test.js` file. However, I can't find the snapshot tests anywhere. This is your file structure as I have it in this branch

snapshots

**Comment by ridwanediallo** [comment]
@TedLivist, I don't know why it does not generate the snapshot folder but the snapshot tests are passing.

**Comment by TedLivist** [comment]
@ridwanediallo maybe you could include a screenshot of where the snapshots tests are added.

I have searched your test files and there is no line that tests for snapshots.

If you had snapshot tests, there should probably be a line like so in your tests files:
```
...
expect(navbar).toMatchSnapshot();
```
I can't find the files containing these lines. Just in case you are mistaken, tests, renders and user simulations using RTL `(@testing-library/react)` are different from snapshot tests.

**Comment by ridwanediallo** [comment]
@TedLivist I tried to do the snapshot this way
 ```
...
expect(navbar).toMatchSnapshot();
```
but I was getting some errors and I was just testing the component to see if it render to the document like this : 
```
test('should render Home', () => {
  const { container } = render(<Home />);
  expect(container).toBeInTheDocument();
});
```
I was then thinking that I was doing the snapshot. And now I am noticing that I was only testing the components.
Still, when I tried to do the snapshot I got the same error. But after downgrading my react version to 17 it is now working.

**Review by keroloussamy — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

clap



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ridwanediallo** [comment]
@keroloussamy Thank you!

**Pull request merged**
